package mnj.mfg.model.lovs;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 29 14:51:39 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class buyerImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public buyerImpl() {
    }

    /**
     * Returns the variable value for P_CUSTOMER.
     * @return variable value for P_CUSTOMER
     */
    public String getP_CUSTOMER() {
        return (String)ensureVariableManager().getVariableValue("P_CUSTOMER");
    }

    /**
     * Sets <code>value</code> for variable P_CUSTOMER.
     * @param value value to bind as P_CUSTOMER
     */
    public void setP_CUSTOMER(String value) {
        ensureVariableManager().setVariableValue("P_CUSTOMER", value);
    }
}
