package mnj.mfg.model.lovs;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 04 19:26:05 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BUYERLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BUYERLOVImpl() {
    }
}
