package mnj.mfg.model.lovs;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 29 18:58:40 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class employLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public employLOVImpl() {
    }

    /**
     * Returns the bind variable value for P_ORG_ID.
     * @return bind variable value for P_ORG_ID
     */
    public String getP_ORG_ID() {
        return (String)getNamedWhereClauseParam("P_ORG_ID");
    }

    /**
     * Sets <code>value</code> for bind variable P_ORG_ID.
     * @param value value to bind as P_ORG_ID
     */
    public void setP_ORG_ID(String value) {
        setNamedWhereClauseParam("P_ORG_ID", value);
    }
}
