package mnj.mfg.model.lovs;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 30 12:16:55 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class patternLovImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public patternLovImpl() {
    }

    /**
     * Returns the bind variable value for P_BUYER_ID.
     * @return bind variable value for P_BUYER_ID
     */
    public String getP_BUYER_ID() {
        return (String)getNamedWhereClauseParam("P_BUYER_ID");
    }

    /**
     * Sets <code>value</code> for bind variable P_BUYER_ID.
     * @param value value to bind as P_BUYER_ID
     */
    public void setP_BUYER_ID(String value) {
        setNamedWhereClauseParam("P_BUYER_ID", value);
    }

    /**
     * Returns the bind variable value for P_STYLE.
     * @return bind variable value for P_STYLE
     */
    public String getP_STYLE() {
        return (String)getNamedWhereClauseParam("P_STYLE");
    }

    /**
     * Sets <code>value</code> for bind variable P_STYLE.
     * @param value value to bind as P_STYLE
     */
    public void setP_STYLE(String value) {
        setNamedWhereClauseParam("P_STYLE", value);
    }

    /**
     * Returns the bind variable value for P_CUT_NO.
     * @return bind variable value for P_CUT_NO
     */
    public String getP_CUT_NO() {
        return (String)getNamedWhereClauseParam("P_CUT_NO");
    }

    /**
     * Sets <code>value</code> for bind variable P_CUT_NO.
     * @param value value to bind as P_CUT_NO
     */
    public void setP_CUT_NO(String value) {
        setNamedWhereClauseParam("P_CUT_NO", value);
    }
}
