package mnj.mfg.model.lovs;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 29 19:20:55 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class planLovImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public planLovImpl() {
    }


    /**
     * Returns the bind variable value for poc_id.
     * @return bind variable value for poc_id
     */
    public String getpoc_id() {
        return (String)getNamedWhereClauseParam("poc_id");
    }

    /**
     * Sets <code>value</code> for bind variable poc_id.
     * @param value value to bind as poc_id
     */
    public void setpoc_id(String value) {
        setNamedWhereClauseParam("poc_id", value);
    }
}
