package mnj.mfg.model.lovs;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 29 19:59:30 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class planNumberImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public planNumberImpl() {
    }

    /**
     * Returns the bind variable value for ratioplan_number.
     * @return bind variable value for ratioplan_number
     */
    public String getratioplan_number() {
        return (String)getNamedWhereClauseParam("ratioplan_number");
    }

    /**
     * Sets <code>value</code> for bind variable ratioplan_number.
     * @param value value to bind as ratioplan_number
     */
    public void setratioplan_number(String value) {
        setNamedWhereClauseParam("ratioplan_number", value);
    }
}
