package mnj.mfg.model.lovs;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 29 15:01:23 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StyleLovImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public StyleLovImpl() {
    }


    /**
     * Returns the bind variable value for p_customerID.
     * @return bind variable value for p_customerID
     */
    public String getp_customerID() {
        return (String)getNamedWhereClauseParam("p_customerID");
    }

    /**
     * Sets <code>value</code> for bind variable p_customerID.
     * @param value value to bind as p_customerID
     */
    public void setp_customerID(String value) {
        setNamedWhereClauseParam("p_customerID", value);
    }

    /**
     * Returns the bind variable value for p_org_id.
     * @return bind variable value for p_org_id
     */
    public String getp_org_id() {
        return (String)getNamedWhereClauseParam("p_org_id");
    }

    /**
     * Sets <code>value</code> for bind variable p_org_id.
     * @param value value to bind as p_org_id
     */
    public void setp_org_id(String value) {
        setNamedWhereClauseParam("p_org_id", value);
    }
}
