package mnj.mfg.model.server;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import mnj.mfg.model.lovs.operatingUnitsVOImpl;
import mnj.mfg.model.server.common.AppModule;
import mnj.mfg.model.views.LinesVOImpl;

import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;

import oracle.jdbc.OracleTypes;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 30 12:45:26 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for HeaderVO1.
     * @return HeaderVO1
     */
    public ViewObjectImpl getHeaderVO1() {
        return (ViewObjectImpl)findViewObject("HeaderVO1");
    }

    /**
     * Container's getter for LinesVO1.
     * @return LinesVO1
     */
    public LinesVOImpl getLinesVO1() {
        return (LinesVOImpl)findViewObject("LinesVO1");
    }

    /**
     * Container's getter for HeaderLineVL1.
     * @return HeaderLineVL1
     */
    public ViewLinkImpl getHeaderLineVL1() {
        return (ViewLinkImpl)findViewLink("HeaderLineVL1");
    }
    
    public void setSessionValues(String orgId, String userId, String respId,
                                 String respAppl) {
    
        

        if (userId != null) {
           //String flag = getFlagValue(userId, respId);
            FacesContext fctx = FacesContext.getCurrentInstance();
            ExternalContext ectx = fctx.getExternalContext();
            HttpSession userSession = (HttpSession)ectx.getSession(false);
            //userSession.setAttribute("Flag", flag);
            userSession.setAttribute("userId", userId);
            userSession.setAttribute("orgId", orgId);
            userSession.setAttribute("respId", respId);
            userSession.setAttribute("unitName", getUnitName(orgId));
        }
    }


    public String getUnitName (String orgId){
        
        ViewObject vo = getoperatingUnitsVO1();
        vo.setWhereClause("ORGANIZATION_ID = "+orgId);
        vo.executeQuery();
        String name = null;
        vo.first();
        
        try {
            name = vo.getCurrentRow().getAttribute("Name").toString();
        } catch (Exception e) {
            // TODO: Add catch code
            e.printStackTrace();
        }
        return name ;
            
    }
    
  //select h.organization_id ,h.name from hr_operating_units h


    /**
     * Container's getter for operatingUnitsVO1.
     * @return operatingUnitsVO1
     */
    public operatingUnitsVOImpl getoperatingUnitsVO1() {
        return (operatingUnitsVOImpl)findViewObject("operatingUnitsVO1");
    }


    /******************************************/

     public String getBuyerDescription(int P_Buyer_ID) {
            String BuyerName = null;
            String stmt =
                "BEGIN :1 := Get_Buyer_Desc(:2)  ; end;";

            java.sql.CallableStatement cs =
                getDBTransaction().createCallableStatement(stmt, 1);

            try {
                cs.registerOutParameter(1, OracleTypes.VARCHAR);
                

                cs.setInt(2, P_Buyer_ID);
               
                cs.execute();
                BuyerName = cs.getString(1);
         
                cs.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
            return BuyerName;
        }
    /*************************************************/



}
