package mnj.mfg.model.server.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 30 12:54:19 PKT 2016
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    String getUnitName(String orgId);

    void setSessionValues(String orgId, String userId, String respId,
                          String respAppl);
}
